# Generated by Django 5.0.1 on 2025-07-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0002_alter_transactions_attachment_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='attachment_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
