# Generated by Django 5.2.4 on 2025-07-22 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0003_alter_transactions_attachment_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
    ]
