# Generated by Django 5.2.4 on 2025-07-22 14:34

import FinanceApp.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0004_remove_users_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('objects', FinanceApp.manager.UserManager()),
            ],
        ),
    ]
