# Generated by Django 5.2.4 on 2025-07-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0005_alter_users_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='password_hash',
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(db_column='password_hash', max_length=255),
        ),
    ]
